### ISSUE TITLE
Change foreground

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#10]
You may want other or no foreground colour in the messages. Or even different colour depending of the writer.

**Comment by ChristianPauly** [comment]
Hm, which color do you mean exactly? The purple background at the received messages?

**Comment by ChristianPauly** [comment]
My idea was to define this as the "main-color" which you can then change in settings -> themes to your personal favourite color. I would more like to make the users more distinguishable by set a color and the first two letters of his username as user avatar (if the user has no avatar)

**Comment by CesarHerreraG** [comment]
Ok
