### ISSUE TITLE
add separators for different kinds of chats. 

### ISSUE THREAD

**Issue by PhoenixLandPirate** [ChristianPauly/fluffychat#100]
These separators make it easier to find the chats that you want as theyre categorised.

These categories are "favourites", "people", "rooms", "low priority" and "system alerts"

![screenshot_20190203-161253_riot_x](https://user-images.githubusercontent.com/8162805/52179179-eb8ad000-27ce-11e9-9e44-e7cdf9fb5513.png)

**Comment by ChristianPauly** [comment]
Hey, thanks for your suggestion. But that does not fit in the UX I want to reach with FluffyChat. Please read my blogpost about this topic: https://www.patreon.com/posts/what-fluffychat-23575662

FluffyChat should have a UX which is similar to Telegram or Whatsapp. So no room tags, no sorting of the rooms and so on. It is a simple instant messenger and not a powerful collaboration tool. To create a more feature rich tool like Riot, we need much more manpower.
