### ISSUE TITLE
+1 appears when there are new messages.

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#106]
It would be interesting that the rooms with new sentences were not only with +1, but with the real number of new sentences.

**Comment by ChristianPauly** [comment]
+1 is only for rooms with no notifications. If you turn on notifications you will see the real number of new messages. Otherwise you will only see that there are new messages but not how much. Thats not implemented in the matrix.org protocol.

**Comment by CesarHerreraG** [comment]
Thanks.

**Comment by CesarHerreraG** [comment]
I don't know how to do it. Even when I select notifications I don't see the number of new messages.

**Comment by ChristianPauly** [comment]
I can confirm that there might be a bug. Sometimes I have the +1 in chats, where I have notifications on. This should not happen.

**Comment by CesarHerreraG** [comment]
Ok.

**Comment by CesarHerreraG** [comment]
Ok. Checked wirh notifications. You may close the issue. Thanks.
