### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by 3arn0wl** [ChristianPauly/fluffychat#119]
Hi

I was just wondering how to put my own choice of background image: the Snap version doesn't recognise any of the apps on my laptop.

**Comment by ChristianPauly** [comment]
Hey :-) this is related to: #110 ContentHub is only existing on Ubuntu Touch so I need to implement the normal Qt Filechooser for the desktop version. This doesn't have a high priority at the moment because of my work on e2e encryption. Contributions are very welcome.
