### ISSUE TITLE
search broken when no search result is found

### ISSUE THREAD

**Issue by Danfro** [ChristianPauly/fluffychat#120]
Using FluffyChat V 11.1 on BQ E5 with RC channel

1. When doing a search with no results after pressing the back button I get presented an empty screen.
- tap search
- enter a word that is not a name (see 2.) or anything that will not deliver a search result
- tap the back button
-> empty screen is presented

2. Search seems to look up only names of chat members. It is not a full text search as the search default text seems to imply "search through all your chats" (Durchsuche alle deine Chats...)

log: [pastebin log](https://paste.ubuntu.com/p/RN4FxBxx58/)

![screenshot20190414_092744434](https://user-images.githubusercontent.com/37637312/56089726-9c7cad80-5e97-11e9-8bb5-ab523da23ee1.png)

**Comment by ChristianPauly** [comment]
Thanks, is fixed in the latest commit.
