### ISSUE TITLE
[wishlist] Online tool to manage translations

### ISSUE THREAD

**Issue by advocatux** [ChristianPauly/fluffychat#13]
It would very convenient for translators if you set an online tool to manage Fluffychats translations, like Weblate, or Transifex to name a couple of examples.

Thank you, and keep up your great job!

**Comment by ChristianPauly** [comment]
Will come in the future, when all matrix features are implemented. At the moment the basic .pot file is changing every day.

**Comment by advocatux** [comment]
> At the moment the basic .pot file is changing every day.

Exactly, that's why a translation tool would be very convenient because it only shows the new strings to translate.

Anyway, I understand the priorities in the project and what have to be develop first :)
