### ISSUE TITLE
Logo proposal for your project.

### ISSUE THREAD

**Issue by fabiyamada** [ChristianPauly/fluffychat#16]
Hello! I am a graphic designer and would like to help you have a nice logo :) 

## Here are my proposals:
![logo propossals](https://user-images.githubusercontent.com/33674731/41997862-6ed3a282-7a16-11e8-8ab8-b9535f9d650c.jpg)

I worked with the idea of "fluffy" and of course "chat"; playing with the meaning of the word in English and French. Or only in English.

The colors can be changed according to your taste; and also I can make adjustments to any of the versions you chose as favorite to use.

I used a font that is nice and friendly and it has Open Font License so there is no problem to use it.

I am doing this for free :) I hope you like a proposal and we can work further to make it perfect for your project! I can provide PNG, AI, SVG files.

Greetings!

**Comment by ChristianPauly** [comment]
Wow AWESOME! You are great! I love your designs! Can you join the group #fluffychat:matrix.org ?
I would really like to use one of these for the logo and for the .desktop icon. I didn't know, that chat=cat in french. :D 
The current main color in FluffyChat is #5625BA. Would the logo look good with this too?

**Comment by ChristianPauly** [comment]
Logo is implemented now. Thank you for your hard work! :-)
