### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by Amolith** [ChristianPauly/fluffychat#21]
I'd love the ability to add more than one Matrix account to FluffyChat!

**Comment by ChristianPauly** [comment]
I am not sure that I will implement this in the future. When Fluffy is featurecomplete, I will see how this could fit in the GUI. This app should be as easy as possible and multiple accounts are often confusing for new users.

**Comment by CesarHerreraG** [comment]
For the moment you can start uMatriks with an account and FluffyChat with another.

**Comment by ChristianPauly** [comment]
Fluffychat will stay one account only. Multiple accounts are complicated and can be confusing. There is also uMatriks for another account and it should be easy to fork uMatriks or fluffychat if someone need 3 accountsmore or more. Sorry :-/
