### ISSUE TITLE
Number of new messages

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#22]
uMatriks shows for each room the number of new messages. It would be interesting having it here.

**Comment by CesarHerreraG** [comment]
I recall it was there in the beginning. But now, althow I have notifications they are not shown.

**Comment by CesarHerreraG** [comment]
Now I have them. :)

**Comment by ChristianPauly** [comment]
Great. I am glad that its working now. Do you know what has changed? Do you also use Riot Web with this account? Sometimes I have recognized that Riot disables notifications for some rooms.

**Comment by CesarHerreraG** [comment]
I use riot. Don't know more. Thanks.
