### ISSUE TITLE
Name of your accound

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#23]
I don't know how to see the account I used to enter FluffyChat.

**Comment by ChristianPauly** [comment]
Im going to find a solution for this in the next releases. The main goal is to make the account name obsolet and use email and phone number to find friends.

**Comment by CesarHerreraG** [comment]
:)

**Comment by ChristianPauly** [comment]
![screenshot20180914_110105576](https://user-images.githubusercontent.com/24619905/45540768-96452680-b80d-11e8-925a-903e90466815.png)
In the new "Add Contact Page" there is displayed, what the full username of the user is. Also you will see it in your own user profile.
