### ISSUE TITLE
Answer a sentence

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#24]
As in Telegram been able to answer a previous sentence said by someone.

**Comment by ChristianPauly** [comment]
Im interested in implementing this but priority will be end2end encryption and contact discovery first.

**Comment by CesarHerreraG** [comment]
:)

**Comment by ChristianPauly** [comment]
Is implemented in latest commit

**Comment by CesarHerreraG** [comment]
Perfect!!
