### ISSUE TITLE
notifications dont show up

### ISSUE THREAD

**Issue by hans555** [ChristianPauly/fluffychat#29]
Notifications, all enabled on bacon device.
Won't show up in notification list in top bar.
Enabled in settings, enabled for fluffychat. This is on 510 development branch

**Comment by ChristianPauly** [comment]
Hi there. :)
I have some questions first:
- At the main page, is there the number of new messages displayed for each chat?
- Have you tried to logout and login?
- Do you have an Ubuntu One account in the system settings?
- When you go into fluffychat -> Settings -> Notifications -> Targets: Is there a device "UbuntuPhone"?
- Do notifications work with Telegram?

**Comment by hans555** [comment]
Hey :)

> At the main page, is there the number of new messages displayed for each chat?
yes

> have you tried to logout and login?
yes.

> Do you have an Ubuntu One account in the system settings?
yes

> When you go into fluffychat -> Settings -> Notifications -> Targets: Is there a device "UbuntuPhone"?
yes

> Do notifications work with Telegram?
i should check :)

**Comment by ChristianPauly** [comment]
Hmm, strange. Which homeserver are you using? Have you tried another matrix account and checked if notifications then work?

**Comment by hans555** [comment]
Did some additional testing, using matrix.org it works. seems to be a problem of my homeserver!
Riot background notifications does not work either, so this issue doesn't belong here ;) Thank you..

**Comment by ChristianPauly** [comment]
Looks like the push notification feature is still experimental in the matrix protocol. And I think only Riot and FluffyChat have implemented this feature yet, so we are still in undiscovered land :D
