### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by GaudeamusII** [ChristianPauly/fluffychat#3]
I am glad someone is developing an app like fluffychat. After the first installation the notification worked for me. After I deleted the APP, and also removed all folders, the notification no longer works after the new installation. What could that be?
Ubuntu 15.04 (r3)

**Comment by ChristianPauly** [comment]
Hi, thanks for your report! :-) Do the notifications now work with the newest version 0.2.1? What happens, when you switch notifications off and on again? Is there now an error report?

Also it would be great if you can post the last entrys on your ubuntu push log at ~/.cache/upstart/ubuntu-push-client.log

**Comment by GaudeamusII** [comment]
Thanks for the answer. I have installed the new version. I've turned the notifications on and off. No error is reported. There is no entry in the log file. The messages also arrive by push. The arrival of the messages is not signalled. 
** (process:2594): WARNING **: a source with id 'postal' doesn't exist
2018/06/06 22:28:46.420476 INFO connectivity check passed.
2018/06/06 22:45:05.665572 INFO connectivity check passed.
2018/06/06 23:02:11.048489 INFO connectivity check passed.
2018/06/06 23:12:11.257397 INFO connectivity check passed.
2018/06/06 23:22:11.416727 INFO connectivity check passed.

**Comment by ChristianPauly** [comment]
So now you receive push notifications but the push notifications are not signalled? Means that the notifications are now persistent in the notification center and you get the green symbol at the top but there is no message bubble, no sound and no vibration?

**Comment by GaudeamusII** [comment]
The message is in the APP. But no green light up, no sound, no vibration

**Comment by ChristianPauly** [comment]
Hm ... Can you test push notifications with another account?
I guess this is caused by push rules, that are set somehow. In a future release, I will make a GUI to edit push rules, so that this should be fixed.

**Comment by GaudeamusII** [comment]
I have now created an account from matrix.org, and there it works. It does not work on my home server (chat.regionetz.net). The message arrives, but is not signaled as new in the APP. With Android and Apple devices the notification from my home server works. Another account on my home server doesn't work either.  How can I delete and reinstall all settings?

**Comment by GaudeamusII** [comment]
I have now uninstalled the app, deleted the folders under.cache and userdata. Now everything works THANK YOU

**Comment by ChristianPauly** [comment]
Glad to here this. :-)
I will let this issue open some time. Maybe other users will have the same problem. I am still not sure, what this is causing.

**Comment by ChristianPauly** [comment]
Hm, interesting. Now I have got the same error. But on other clients like Riot web I also got no notifications. After I relogged in riot web, the problem was gone. So definetly the matrix.org server has not sent any notifications. Its not a problem of the push gateway or the app I think.

**Comment by GaudeamusII** [comment]
I'm fine now. I don't know how the PUSH service works, though. I can offer you (PN) to create an account on my server. Here I can make a TCPDump. Which port should the push notification go through?

**Comment by ChristianPauly** [comment]
Its really depending on push rules. I have found out, that my push rules are:

qml: {"device":{},"global":{"content":[{"default":true,"pattern":"krillechritzelius","enabled":true,"rule_id":".m.rule.contains_user_name","actions":["notify",{"set_tweak":"sound","value":"default"},{"set_tweak":"highlight"}]}],"override":[{"default":true,"enabled":false,"conditions":[],"rule_id":".m.rule.master","actions":["dont_notify"]},{"default":true,"enabled":true,"conditions":[{"pattern":"m.notice","kind":"event_match","key":"content.msgtype"}],"rule_id":".m.rule.suppress_notices","actions":["dont_notify"]},{"default":true,"enabled":true,"conditions":[{"pattern":"m.room.member","kind":"event_match","key":"type"},{"pattern":"invite","kind":"event_match","key":"content.membership"},{"pattern":"@krillechritzelius:matrix.org","kind":"event_match","key":"state_key"}],"rule_id":".m.rule.invite_for_me","actions":["notify",{"set_tweak":"sound","value":"default"},{"set_tweak":"highlight","value":false}]},{"default":true,"enabled":true,"conditions":[{"pattern":"m.room.member","kind":"event_match","key":"type"}],"rule_id":".m.rule.member_event","actions":["dont_notify"]},{"default":true,"enabled":true,"conditions":[{"kind":"contains_display_name"}],"rule_id":".m.rule.contains_display_name","actions":["notify",{"set_tweak":"sound","value":"default"},{"set_tweak":"highlight"}]},{"default":true,"enabled":true,"conditions":[{"pattern":"@room","kind":"event_match","key":"content.body"},{"kind":"sender_notification_permission","key":"room"}],"rule_id":".m.rule.roomnotif","actions":["notify",{"set_tweak":"highlight","value":true}]}],"sender":[],"room":[],"underride":[{"default":true,"enabled":true,"conditions":[{"pattern":"m.call.invite","kind":"event_match","key":"type"}],"rule_id":".m.rule.call","actions":["notify",{"set_tweak":"sound","value":"ring"},{"set_tweak":"highlight","value":false}]},{"default":true,"enabled":true,"conditions":[{"kind":"room_member_count","is":"2"},{"pattern":"m.room.message","kind":"event_match","key":"type"}],"rule_id":".m.rule.room_one_to_one","actions":["notify",{"set_tweak":"sound","value":"default"},{"set_tweak":"highlight","value":false}]},{"default":true,"enabled":true,"conditions":[{"kind":"room_member_count","is":"2"},{"pattern":"m.room.encrypted","kind":"event_match","key":"type"}],"rule_id":".m.rule.encrypted_room_one_to_one","actions":["notify",{"set_tweak":"sound","value":"default"},{"set_tweak":"highlight","value":false}]},{"default":true,"enabled":true,"conditions":[{"pattern":"m.room.message","kind":"event_match","key":"type"}],"rule_id":".m.rule.message","actions":["notify",{"set_tweak":"highlight","value":false}]},{"default":true,"enabled":true,"conditions":[{"pattern":"m.room.encrypted","kind":"event_match","key":"type"}],"rule_id":".m.rule.encrypted","actions":["notify",{"set_tweak":"highlight","value":false}]}]}}

Made by the riot web. I think that riot web wants to disable all push notifications, when you are using it a certain time but forgets to reenable it then. xD
I think I will just implement, that all push rules will be killed, when you turn on the notifications. But globally this seems to be a bug in riot web ...
