### ISSUE TITLE
Chat previews hard to read in dark theme

### ISSUE THREAD

**Issue by userj** [ChristianPauly/fluffychat#30]
![screenshot20180927_084002386](https://user-images.githubusercontent.com/3128635/46157845-7a8c4800-c231-11e8-9ea6-6e62639b1fe1.png)
See screenshot.
Chat previews are a dark gray, and the background is black in dark theme. So, it's difficult to read the previews unless screen is at a higher brightness. A slightly lighter shade of gray would improve this.

**Comment by ChristianPauly** [comment]
Fixed in https://github.com/ChristianPauly/fluffychat/commit/933a0ec9b53fdbd0916376f890c4d21c6dbdad6f

Thank you for your report :+1:
