### ISSUE TITLE
Copy a message

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#4]
It woul be interesting may copy a message into clipboard.

**Comment by ChristianPauly** [comment]
Don't worry, this will come in the near future! :-D

**Comment by CesarHerreraG** [comment]
Thanks.

**Comment by 3arn0wl** [comment]
On a related note, I tried to paste a link into FluffyChat yesterday, and that didn't work. Can I assume that you're working on this too?

Incidentally - Thank you SO MUCH for UT FluffyChat: It's really set the cat among the pigeons! People are really liking it (especially the notification feature and the account set-up facility), and are being tempted away from Telegram to Matrix. So well done! And keep up the good work. (Did you see the latest UT blog-post on Matrix?)

**Comment by ChristianPauly** [comment]
Hm, copy something and paste it into the FluffyChat message input seems working fine to me. I will keep an eye on this. Maybe its just fixed somehow in the newest version, which is not in the openstore right now.
Thank you very much for the blog post. I really liked it! :-) I should mention that in the next version the notifications will be enabled automatically by default.

**Comment by CesarHerreraG** [comment]
Thanks Christian.

**Comment by 3arn0wl** [comment]
Excellent. Thank you


On Friday, 22 June 2018 07:18:57 CDT, Christian <notifications@github.com> 
wrote:
> Hm, copy something and paste it into the FluffyChat message 
> input seems working fine to me. I will keep an eye on this. 
> Maybe its just fixed somehow in the newest version, which is not 
> in the openstore right now.
> Thank you very much for the blog post. I really liked it! :-) I 
> should mention that in the next version the notifications will 
> be enabled automatically by default.
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by ChristianPauly** [comment]
The new version is out now. Can you confirm, that copy text and paste into the message input field is now working?

**Comment by advocatux** [comment]
I can confirm copy&paste into the message input field work on both versions (vivid and xenial)

**Comment by CesarHerreraG** [comment]
I can paste in the line of writing but I can't copy the text in a written message. BQ E4.5  vivid.

**Comment by CesarHerreraG** [comment]
I can copy text in the line of writing too.

**Comment by CesarHerreraG** [comment]
I'd like to copy a written message.

**Comment by ChristianPauly** [comment]
Is implemented in fluffychat 0.6.x

**Comment by CesarHerreraG** [comment]
:)
