### ISSUE TITLE
Too many notifications for new messages

### ISSUE THREAD

**Issue by mattbel10** [ChristianPauly/fluffychat#48]
**Actual behaviour**
When I leave the UT phone shutdown for a while (even for one day or two), I noticed that booting up the phone again I receive a lot of notification bubbles at the same time in the indicators panel above for all the new messages got in a FluffyChat discussion thread, one for each new message received (100 new messages, 100 notifications bubbles). The bubbles are persistent and only a 'clean all' command can wipe the indicator panel.

**Desired behaviour**
1) If the phone was shutdown before and it is booted up and there are more than two notifications for FluffyChat at the same time to be notified to the phone, it should be better to receive only one notification bubble, relevant the last message only.
2) If the phone is already powered and it gets notification bubbles for new messages, the more recent message should be piled above the older message and so on as new messages are received. Then the bubbles pile shall be automatically emptied setting a time delay parameter (5 seconds?), starting from the oldest message bubble until to get to the one just before the newest; the newest message should always remain in the notifications area, until either a new message notification is received, or the UT user tap on the notification bubble to open the relevant chat.

**Comment by mattbel10** [comment]
Christian, if any useful for you, i tried to pay attention to how notification is managed by the Telegram app on Ubuntu Touch: when the phone is powered and working, if more than one message is received for the same chat, it doesn't matter, because only one message is always diplayed in the indicator panel; then this message is updated as soon as a more recent one is received. I feel FluffyChat should work in a similar fashion.

**Comment by userj** [comment]
Yes, it seems that Fluffychat doesn't detect if a message has been read on another chat client already. So, notifications go to both and don't disappear on the Ubuntu Touch device. If you are chatting on Riot.im, then Fluffychat notifications still collect on UT device.

**Comment by ChristianPauly** [comment]
I will switch to a C++ PushHelper for the next version, then this will be fixed. Notifications will be only one per room, so any new notification in a room will override the old and if you have 20 new messages from 4 different rooms, you will have only 4 notifications with the last message of each room.

Also if you have read a message in Riot, the notification will automatically disappear. :-)

**Comment by userj** [comment]
@ChristianPauly sounds great! Thank you :)

**Comment by ChristianPauly** [comment]
Fixed with the new PushHelper :-)
