### ISSUE TITLE
Notifications for each room

### ISSUE THREAD

**Issue by CesarHerreraG** [ChristianPauly/fluffychat#5]
Choose the rooms you want notifications.

**Comment by ChristianPauly** [comment]
Thanks for your request. This will be implemented in the near future. At the moment you can also set the notification behaviours in the Riot web interface.

**Comment by CesarHerreraG** [comment]
Thanks.

**Comment by ChristianPauly** [comment]
Feature is now implemented in the version 0.2.3

**Comment by CesarHerreraG** [comment]
Thanks.
