### ISSUE TITLE
Fix issue in the latest .pot file (2018-06-16 15:45+0000)

### ISSUE THREAD

**Issue by advocatux** [ChristianPauly/fluffychat#9]
The latest .pot file looks like it hasn't been properly generated. See the issue starting at line 252:

https://github.com/ChristianPauly/fluffychat/blob/63cdbfb5086ce13340f843d425486379f586ab90/po/fluffychat.christianpauly.pot#L252-L260

**Comment by ChristianPauly** [comment]
whoops, sorry, will fix this tomorrow :D

**Comment by advocatux** [comment]
It seems you fixed the problem but you kept the typo ;)

https://github.com/ChristianPauly/fluffychat/blob/b3d01c0c43cd26e12e893e5d144543f53dd43fc2/po/fluffychat.christianpauly.pot#L302-L305

**Comment by ChristianPauly** [comment]
fixed :D
