### ISSUE TITLE
World domination (snap package)

### ISSUE THREAD

**Issue by timsueberkrueb** [ChristianPauly/fluffychat#99]
Fluffy chat is the best matrix client out there! Let's create a snap for it :)

**Comment by ChristianPauly** [comment]
Would be awesome :D So what we need for this is the following:

- [ ] Remove HTML5 for uploading media which actually still depends on the old browser engine.
- [ ] Improve the UX and design for convergence. At the moment this is very buggy... (mobile first design)
- [ ] Use QtWebEngine for the privacy policy web viewer
- [ ] Switch to QtQuick Controls for the most parts?
- [ ] Package Ubuntu Components (still need e.g. UbuntuShape and BottomEdge)

**Comment by timsueberkrueb** [comment]
I pushed initial snapcraft configuration to [my fork](https://github.com/timsueberkrueb/fluffychat/tree/initial-snap-config). 
With [this patch of Main.qml](https://paste.ubuntu.com/p/KzrzxbyDqQ/) it starts the application. Not much is working besides signing in though, mainly because I simply commented out what didn't work due to missing dependencies ^^ 
But it's a starting point!

**Comment by ChristianPauly** [comment]
Awesome :D Sorry, I know my code is a mess. I'm currently thinking about a big refactoring so that it is much more intuitivly to understand what is what. Maybe this could also help you

**Comment by timsueberkrueb** [comment]
Current state :)
![screenshot from 2019-02-02 18-11-09](https://user-images.githubusercontent.com/11774614/52167156-2d583f80-2717-11e9-94f7-4a273b522813.png)

**Comment by timsueberkrueb** [comment]
Chatting is working, I have disabled file uploading/stickers because that part is still broken.

**Comment by timsueberkrueb** [comment]
Okay, so the current plan as discussed with @ChristianPauly on Matrix is to wait for some of the desktop-compatibility improvements to land. Then I will update the snapcraft config and file a PR :)

**Comment by ChristianPauly** [comment]
Oxide is removed now. It should work now. @timsueberkrueb You wanna conquer the world? ;)

**Comment by timsueberkrueb** [comment]
Awesome, yes, I'm planning to work on it this weekend.
